# Generated by Django 5.0.7 on 2024-07-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('serie', 'Serie'), ('pelicula', 'Película')], max_length=10)),
                ('fecha_transmision', models.IntegerField(blank=True, null=True)),
                ('temporada', models.IntegerField(blank=True, null=True)),
                ('duracion_capitulo', models.DurationField(blank=True, null=True)),
                ('calidad', models.CharField(blank=True, max_length=20, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('capitulo', models.FileField(blank=True, null=True, upload_to='capitulos/')),
                ('genero', models.ManyToManyField(to='taskcrud.genero')),
                ('idiomas', models.ManyToManyField(to='taskcrud.idioma')),
                ('subtitulo', models.ManyToManyField(to='taskcrud.subtitulo')),
            ],
        ),
    ]
