# Generated by Django 5.0.7 on 2024-07-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcrud', '0002_episodio_media_episodios'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='numero_episodios',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
